# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      timezone: Europe/Paris
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: composer
    directories:
      - "/"
      - "/vendor-bin/cs-fixer"
      - "/vendor-bin/openapi-extractor"
      - "/vendor-bin/phpunit"
      - "/vendor-bin/psalm"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
